services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 4500:4500
